export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGOUT = 'LOGUOT'

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const ENTER_COUNT='ENTER_COUNT'
export const EXIT_COUNT='EXIT_COUNT'
export const FILL_COUNTS="FILL_COUNTS"
export const FILL_DATES='FILL_DATES'

export const CLEAN_UP='CLEAN_UP'